src/core/default_config.cfg
src/core/enums.rs

- feat: translate format type
- refactor: format files
- feat: add default config

adding default config

---

.github/workflows/pr.yaml
src/core/parser/lexer.rs

- ci: add formatting check to pr
- feat: fixing build issues

adding fmt check rust

---

src/core/parser/segments/base.rs
src/utils/reflow/depth_map.rs

- feat: implement hash function
- feat: implement stack position

implement stack position

---

src/core/dialects/base.rs
src/core/parser/lexer.rs
src/core/templaters/base.rs
src/dialects/ansi.rs

- feat: implement the regex lexer
- temp

working on lexer itself

---

src/core/config.rs
src/core/errors.rs
src/core/parser/lexer.rs
src/core/parser/markers.rs
src/core/parser/segments/base.rs

- feat: implement violations from segments
- refactor: slight optimization where using iterators

slight optimization

---

src/core/config.rs
src/core/linter/common.rs
src/core/linter/linter.rs
src/core/parser/lexer.rs
src/core/templaters/base.rs

- feat: working on lexer
- feat: making progress

working up to lex

---

src/core/templaters/base.rs

- temp implementing futher tests
- temp making progress

translating templat file tests

---

src/core/slice_helpers.rs
src/core/templaters/base.rs

- feat: implementing TemplatedFile tests
- feat: implementting final templating methods and tests

implementing templating methods

---

src/core/parser/segments.rs
src/core/parser/segments/base.rs
src/core/parser/segments/fix.rs

- feat: adding skeleton for file segment
- feat: moving fix to match sqlfluff

adding fix implementations

---

src/core/parser/markers.rs
src/core/parser/segments.rs
src/core/parser/segments/base.rs
src/core/parser/segments/common.rs
src/core/parser/segments/file.rs
src/core/parser/segments/raw.rs
src/core/parser/segments/test_functions.rs

- feat: implementing all ANSI lexers but have error
- fixed ansi lexers but giving loop
- feat: implementing segments

implementing segments

---

src/core/linter/linted_file.rs
src/core/templaters/base.rs

- feat: implementing file lint method
- feat: implementing linted file code

further implementing functions

---

.github/workflows/pr.yaml

With the intent to speed up CI times, this follows the advice of: https://matklad.github.io/2021/09/04/fast-rust-builds.html#CI-Workflow

chore: improve CI

---

.github/workflows/release.yml

- **ci: adding checksums to the releases**

adding checksums to releases

---

crates/cli/src/main.rs
crates/lib/src/core/config.rs
crates/lib/src/core/default_config.cfg
crates/lib/src/core/linter/linter.rs
crates/lib/src/core/parser/grammar/sequence.rs
crates/lib/src/core/parser/parser.rs
crates/lib/src/core/rules/base.rs
crates/lib/src/core/rules/context.rs
crates/lib/src/lib.rs
crates/lib/src/rules/l001.rs
crates/lib/src/rules/layout.rs
crates/lib/src/rules/layout/LT01.rs
crates/lib/src/rules/layout/LT02.rs
crates/lib/src/rules/layout/LT05.rs
crates/lib/src/utils/reflow/config.rs
crates/lib/src/utils/reflow/sequence.rs

chore: enhanced configuration management

---

crates/lib/src/cli/formatters.rs
crates/lib/src/core/rules/base.rs
crates/lib/src/rules/aliasing/AL01.rs
crates/lib/src/rules/aliasing/AL02.rs
crates/lib/src/rules/aliasing/AL04.rs
crates/lib/src/rules/aliasing/AL05.rs
crates/lib/src/rules/aliasing/AL08.rs
crates/lib/src/rules/convention/CV02.rs
crates/lib/src/rules/l001.rs
crates/lib/src/rules/layout/LT01.rs
crates/lib/src/rules/layout/LT02.rs
crates/lib/src/rules/layout/LT03.rs
crates/lib/src/rules/layout/LT04.rs
crates/lib/src/rules/layout/LT05.rs
crates/lib/src/rules/layout/LT07.rs
crates/lib/src/rules/layout/LT08.rs
crates/lib/src/rules/layout/LT10.rs
crates/lib/src/rules/layout/LT11.rs
crates/lib/src/rules/structure/ST01.rs
crates/lib/src/rules/structure/ST02.rs
crates/lib/src/rules/structure/ST03.rs

chore: add descriptions to all rules

---

crates/cli/src/commands.rs
crates/cli/src/main.rs

basic testing performed here: https://github.com/gvozdvmozgu/sqruff-project/pull/1/files

chore: new format for github annotation output

---

.github/workflows/release.yml
Cargo.lock
crates/cli/Cargo.toml
crates/lib/Cargo.toml

- **ci: add permissions to update homebrew**
- **chore: bump to version 0 1 2**

adding permissions repo

---

crates/lib/src/core/parser/match_algorithms.rs
crates/lib/src/core/parser/segments/base.rs
crates/lib/src/core/parser/segments/common.rs
crates/lib/src/core/parser/segments/keyword.rs
crates/lib/src/core/parser/segments/meta.rs
crates/lib/src/core/rules/crawlers.rs
crates/lib/src/dialects/ansi.rs
crates/lib/src/utils/reflow/config.rs
crates/lib/src/utils/reflow/depth_map.rs
crates/lib/src/utils/reflow/elements.rs
crates/lib/src/utils/reflow/rebreak.rs
crates/lib/src/utils/reflow/reindent.rs

- before: 4.46, 4.55, 4.65 s measurements
- after: 3.75, 3.66, 3.63 s measurements
- which makes for a near 20% improvement in the benchmark
- measurements aren't super robust but nice little win

feat: make faster by not using strings

---

crates/lib/src/core/parser/context.rs
crates/lib/src/core/parser/grammar/anyof.rs
crates/lib/src/core/parser/grammar/base.rs
crates/lib/src/core/parser/grammar/delimited.rs
crates/lib/src/core/parser/grammar/noncode.rs
crates/lib/src/core/parser/grammar/sequence.rs
crates/lib/src/core/parser/matchable.rs
crates/lib/src/core/parser/parsers.rs

- went from 2.66s on before to 2.44s after

feat: 5% faster by using uuid

---

crates/cli/src/main.rs

fix: resolve config unwrap error in `--help` command

---

crates/lib/src/dialects/bigquery.rs
crates/lib/src/rules/aliasing/AL01.rs
crates/lib/src/utils/analysis/select.rs

fix: BigQuery dialect linting issues: remove duplicate AS and incorrect alias handling

---

.hacking/update_homebrew_pr.sh
Cargo.lock
crates/cli/Cargo.toml
crates/lib/Cargo.toml

- **ci: fix which ones we override**
- **chore: bump version**

working on more precise sed

---

crates/lib/src/core/config.rs
crates/lib/src/core/parser/segments/base.rs
crates/lib/src/dialects/ansi.rs
crates/lib/src/dialects/bigquery.rs
crates/lib/src/rules/aliasing/AL05.rs
crates/lib/src/rules/references/RF01.rs
crates/lib/src/utils/analysis/select.rs

fix: correct `AS` alias handling in BigQuery queries (issue #307)

---

crates/cli/src/main.rs

fix: Improve error reporting in CLI lint command

---

.github/workflows/pr.yaml
Cargo.lock
crates/lib/Cargo.toml

chore(ci): add wasm32-unknown-unknown target to CI build

---

Cargo.lock
crates/lib/Cargo.toml
crates/lib/src/utils/reflow/depth_map.rs
crates/lib/src/utils/reflow/elements.rs

…t` for `stack_hash_set` and `stack_positions` in DepthInfo.

refactor: replaced `AHashMap` and `AHashSet` with `IntMap` and `IntSet` for `stack_hash_set` and `stack_positions` in DepthInfo

---

crates/lib/src/core/dialects/base.rs
crates/lib/src/core/parser/grammar/sequence.rs
crates/lib/src/core/parser/match_algorithms.rs
crates/lib/src/dialects/ansi.rs
crates/lib/src/dialects/bigquery.rs

feat: small optimisation

---

.github/workflows/docs.yml
Cargo.lock
crates/cli/Cargo.toml
crates/cli/src/main.rs
options.md

feat: Add clap-markdown integration for documentation generation

---

.hacking/check_versions_match.sh
Cargo.lock
crates/cli/Cargo.toml
crates/lib/Cargo.toml
crates/lsp/Cargo.toml
editors/code/package.json

- **ci: adding lsp carate to check versions**
- **chore: bump version to 0.7.1**

chore: bump version to 0.7.1

---

.github/workflows/release.yml
Cargo.lock
crates/cli/Cargo.toml
crates/lib/Cargo.toml
crates/lsp/Cargo.toml
editors/code/package.json

- **fix: fix release job for vsix**
- **chore: bump version to 0.7.2**

fix for release job

---

editors/code/package-lock.json
editors/code/package.json

- **devex: add ability to open ansi folder**
- **feat: slight tweaks to make it look nicer**

add target folder to run in browser

---

Cargo.lock
Cargo.toml
README.md
crates/cli/Cargo.toml
crates/lsp/Cargo.toml
editors/code/README.md
editors/code/package-lock.json
editors/code/package.json

- add sparksql to documentation

chore: bump release 080

---

editors/code/package-lock.json
editors/code/package.json

- need to update engine to be able to package

chore: further node updates and package fix

---

crates/lib/src/core/parser/context.rs
crates/lib/src/core/parser/grammar/anyof.rs
crates/lib/src/core/parser/grammar/base.rs
crates/lib/src/core/parser/grammar/delimited.rs
crates/lib/src/core/parser/grammar/noncode.rs
crates/lib/src/core/parser/grammar/sequence.rs
crates/lib/src/core/parser/matchable.rs
crates/lib/src/core/parser/parsers.rs
crates/lib/src/core/parser/segments/bracketed.rs
crates/lib/src/helpers.rs

Temporary fix to allow more keys while we refactor the full fix.

fix: temporary fix to extend cache key

---

crates/lib/src/dialects/bigquery.rs
crates/lib/src/rules/references.rs
crates/lib/src/rules/references/RF05.rs
crates/lib/test/fixtures/dialects/bigquery/declare_variable.yml
crates/lib/test/fixtures/dialects/bigquery/delete.yml
crates/lib/test/fixtures/dialects/bigquery/export_statement.yml
crates/lib/test/fixtures/dialects/bigquery/for_in.yml
crates/lib/test/fixtures/dialects/bigquery/insert.yml
crates/lib/test/fixtures/dialects/bigquery/select_for_system_time.yml
crates/lib/test/fixtures/dialects/bigquery/select_identifiers.yml
crates/lib/test/fixtures/dialects/bigquery/select_if.yml
crates/lib/test/fixtures/dialects/bigquery/select_ml_predict_with_select.yml
crates/lib/test/fixtures/dialects/bigquery/select_ml_weights.yml
crates/lib/test/fixtures/dialects/bigquery/select_pivot.yml
crates/lib/test/fixtures/dialects/bigquery/select_quoting.yml
crates/lib/test/fixtures/dialects/bigquery/select_udf_quote_everything.yml
crates/lib/test/fixtures/dialects/bigquery/select_udf_quote_nothing.yml
crates/lib/test/fixtures/dialects/bigquery/select_udf_quote_project_and_datasetfunctionname.yml
crates/lib/test/fixtures/dialects/bigquery/select_udf_quote_project_name.yml
crates/lib/test/fixtures/dialects/bigquery/select_where_array_element_less_than.yml
crates/lib/test/fixtures/dialects/bigquery/select_where_greater_than.yml
crates/lib/test/fixtures/rules/std_rule_cases/RF05.yml
docs/rules.md

feat: add RF05 rule

---

crates/lib/src/rules/convention/CV07.rs
docs/rules.md

fix: small fix to rule CV07

---

crates/lib/src/rules/aliasing/AL06.rs
crates/lib/src/rules/references.rs
crates/lib/src/rules/references/RF06.rs
crates/lib/src/rules/structure.rs
crates/lib/src/rules/structure/ST04.rs
crates/lib/src/rules/structure/ST06.rs
crates/lib/src/rules/structure/ST07.rs
docs/rules.md

- also fix small typo in rule name

chore: small rule clean up

---

crates/lib/src/rules/layout/LT13.rs

- ran sqruff on all and this obviously failed

feat: actually allow LT13 to run

---

crates/lib/src/core/parser/segments/base.rs
crates/lib/src/core/parser/segments/keyword.rs
crates/lib/src/dialects/ansi.rs
crates/lib/src/rules/aliasing/AL03.rs
crates/lib/src/rules/aliasing/AL05.rs
crates/lib/src/rules/aliasing/AL07.rs
crates/lib/src/rules/aliasing/AL09.rs
crates/lib/src/rules/ambiguous/AM01.rs
crates/lib/src/rules/convention.rs
crates/lib/src/rules/convention/CV05.rs
crates/lib/src/rules/convention/CV06.rs
crates/lib/src/rules/layout/LT06.rs
crates/lib/src/rules/layout/LT09.rs
crates/lib/src/rules/layout/LT10.rs
crates/lib/src/rules/structure/ST01.rs
crates/lib/src/rules/structure/ST02.rs
crates/lib/src/rules/structure/ST04.rs
crates/lib/src/rules/structure/ST08.rs
crates/lib/src/utils/functional/segments.rs
crates/lib/test/fixtures/rules/std_rule_cases/CV06.yml
docs/rules.md

- **temp**
- **temp**
- **tempt**
- **temp**

feat: implementing cv06

---

crates/lib/src/utils/reflow/config.rs
crates/lib/src/utils/reflow/elements.rs

- make things stricter and therefore easier to refactor and potentially
more performant

chore: moving to static strings

---

crates/lib/src/utils/reflow/config.rs
crates/lib/src/utils/reflow/depth_map.rs
crates/lib/src/utils/reflow/sequence.rs

- small removals of to_string where not necessary

chore: move to iterators

---

crates/lib/src/rules/ambiguous.rs
crates/lib/src/rules/ambiguous/AM04.rs
crates/lib/src/utils/analysis/query.rs
crates/lib/test/fixtures/rules/std_rule_cases/AM04.yml
docs/rules.md

feat: working on am04

---

crates/cli/src/docs.rs
crates/cli/src/docs/generate_rule_docs_template.md
crates/lib/src/cli/formatters.rs
crates/lib/src/core/dialects/init.rs
crates/lib/src/core/parser/grammar/anyof.rs
crates/lib/src/core/parser/grammar/base.rs
crates/lib/src/core/parser/parsers.rs
crates/lib/src/core/parser/segments/base.rs
crates/lib/src/core/parser/segments/bracketed.rs
crates/lib/src/core/parser/segments/common.rs
crates/lib/src/core/parser/segments/test_functions.rs
crates/lib/src/core/rules/base.rs
crates/lib/src/dialects/ansi.rs
crates/lib/src/rules.rs
crates/lib/src/rules/ambiguous/AM02.rs
crates/lib/src/rules/convention/CV06.rs
crates/lib/src/rules/convention/CV10.rs
crates/lib/src/rules/convention/CV11.rs
crates/lib/src/rules/references/RF01.rs
crates/lib/src/rules/references/RF03.rs
crates/lib/src/rules/structure.rs
crates/lib/src/rules/structure/ST07.rs
docs/rules.md

- **chore: small clean up of order**
- **refactor: move dialect skipper logic into separate method**

feat: document the skipped rules

---

editors/code/package-lock.json
editors/code/package.json

- **chore: bump @typescript-eslint/parser in /editors/code**
- **chore: dedupe and further update**

chore: update node dependencies

---

crates/cli/src/commands.rs
crates/cli/src/main.rs
crates/lib/src/core/config.rs
docs/cli.md

feat: add optional config file path to CLI

---

editors/code/package-lock.json
editors/code/package.json

- **chore: bump @typescript-eslint/eslint-plugin in /editors/code**
- **chore: bump @typescript-eslint/parser in /editors/code**

bump js updates

---

editors/code/package-lock.json
editors/code/package.json

- **chore: bump @typescript-eslint/parser in /editors/code**
- **chore: bump @typescript-eslint/eslint-plugin in /editors/code**
- **chore: bump @vscode/test-web from 0.0.56 to 0.0.57 in /editors/code**

update deps node sep 2

---

crates/lib/Cargo.toml
crates/lib/src/core/parser/segments/base.rs

Useful for debugging, but tedious to write every time.

chore: add `stringify` feature for `ErasedSegment`

---

Cargo.lock
Cargo.toml
editors/code/package-lock.json
editors/code/package.json

- **fix: make config global**
- **chore: bump version to 15.7**

chore: bump version after fix

---

.github/workflows/deploy.yml
playground/package.json
playground/vite.config.ts

You should configure the repository settings to use GitHub Actions as the source for GitHub Pages

internal: add GitHub Pages deployment workflow

---

Cargo.lock
Cargo.toml
editors/code/package.json

- **fix: make the package work**
- **chore: bump version 0 18 8**

fix for package

---

crates/lib-core/src/dialects/common.rs
crates/lib-core/src/linter.rs
crates/lib-core/src/parser/markers.rs
crates/lib-core/src/parser/segments/base.rs
crates/lib-core/src/rules.rs
crates/lib-core/src/templaters/base.rs
crates/lib/src/core/linter/core.rs
crates/lib/src/core/rules/base.rs
crates/lib/src/core/rules/context.rs
crates/lib/src/rules/aliasing/al01.rs
crates/lib/src/rules/aliasing/al03.rs
crates/lib/src/rules/capitalisation/cp02.rs
crates/lib/src/rules/convention/cv05.rs
crates/lib/src/rules/layout/lt01.rs
crates/lib/src/rules/layout/lt02.rs
crates/lib/src/rules/layout/lt03.rs
crates/lib/src/rules/layout/lt04.rs
crates/lib/src/rules/layout/lt05.rs
crates/lib/src/rules/layout/lt08.rs
crates/lib/src/rules/layout/lt11.rs
crates/lib/src/rules/references/rf03.rs
crates/lib/src/rules/structure/st04.rs
crates/lib/src/rules/structure/st05.rs
crates/lib/src/rules/structure/st08.rs

- **chore: clean up alias info**
- **chore: further cleaning up code**
- **chore: further clean up of things**
- **chore: small clean up**
- **chore: make config not optional in rule context**

chore: clean up code base

---

Cargo.lock
crates/cli/Cargo.toml
crates/cli/src/ignore.rs
crates/cli/src/main.rs
crates/lib/src/core/linter/core.rs

feat: implement sqruffignore

---

crates/lib-core/src/parser/segments/base.rs
crates/lib/src/rules/convention/cv03.rs
crates/lib/src/rules/structure/st05.rs

fix: add `SegmentBuilder::comma` method and update rule usage

---

Cargo.lock
crates/lib/Cargo.toml

- **chore: update rust version**
- **chore: update dependencies after rust**

chore: update deps after rust

---

crates/lib/src/rules/structure/st01.rs
docs/rules.md

docs: fix structure.else_null docs

---

editors/code/package.json
playground/package.json
pnpm-lock.yaml

- **chore: bump @typescript-eslint/parser from 8.16.0 to 8.17.0**
- **chore: bump @typescript-eslint/eslint-plugin from 8.16.0 to 8.17.0**

update eslint again

---

crates/lib-core/src/errors.rs
crates/lib/src/core/linter/core.rs

Revert "feat: add description to SQLParseError and handle unparsable sections in linter"

---

crates/lib-dialects/src/sparksql.rs
crates/lib-dialects/test/fixtures/dialects/sparksql/alter_database.sql
crates/lib-dialects/test/fixtures/dialects/sparksql/alter_database.yml

- **feat: sparsql timestamp ntz and ltz**
- **feat: sparksql alter database set location**

feat: sparksql alter database set location

---

crates/lib-dialects/test/fixtures/dialects/sparksql/select_from_lateral_view.sql
crates/lib-dialects/test/fixtures/dialects/sparksql/select_from_lateral_view.yml
crates/lib-dialects/test/fixtures/dialects/sparksql/select_group_by.sql
crates/lib-dialects/test/fixtures/dialects/sparksql/select_group_by.yml
crates/lib-dialects/test/fixtures/dialects/sparksql/select_qualify.sql
crates/lib-dialects/test/fixtures/dialects/sparksql/select_qualify.yml
crates/lib-dialects/test/fixtures/dialects/sparksql/select_sort_by.sql
crates/lib-dialects/test/fixtures/dialects/sparksql/select_sort_by.yml

- **fix: select cluster by**
- **chore: copy over select group by from sqlfluff**
- **chore: copy over qualify test from sqlfluff**
- **chore: sparksql copy over sort by**
- **chore: mover over lateral view**

chore: copy over tests from sqlfluff

---

crates/lib-dialects/src/sparksql.rs

Revert "refactor: move sparksql describe grammar"

---

crates/lib-dialects/src/sparksql.rs

Revert "Revert "refactor: move sparksql describe grammar""

---

editors/code/package.json
playground/package.json
pnpm-lock.yaml

- **chore: bump @typescript-eslint/eslint-plugin from 8.18.1 to 8.18.2**
- **chore: bump typescript-eslint from 8.18.1 to 8.18.2**

update typescript eslint

---

playground/package.json
pnpm-lock.yaml

- **chore: bump react and @types/react**
- **chore: bump react-dom from 18.3.1 to 19.0.0**

updating react 19

---

crates/lib-core/src/errors.rs

Implement Display for SQLFluffUserError

---

crates/lib-dialects/src/trino.rs
crates/lib-dialects/test/fixtures/dialects/trino/analyze.sql
crates/lib-dialects/test/fixtures/dialects/trino/analyze.yml
crates/lib-dialects/test/fixtures/dialects/trino/comment_on.sql
crates/lib-dialects/test/fixtures/dialects/trino/comment_on.yml

- **feat: add analyze to trino**
- **feat: add trino comment on functionality**

feat: trino comment on and analyze

---

crates/lib/src/rules/ambiguous/am01.rs
docs/rules.md

fix: broken markup in rules.md

---

.github/workflows/python-ci.yml

Sorry I just realized that this bit was missed out from the earlier PR! Hopefully it works this time.

fix:python release

---

crates/lib/src/core/rules/reference.rs
crates/lib/test/fixtures/rules/std_rule_cases/RF01.yml

only contains the test and not the fix yet.

fix: rf01 rule in postgres

---

docs/development.md

- finish the last sentence in development docs
- `git status --short`

Fix docs sentence

---

crates/lib-core/src/dialects/syntax.rs
crates/lib-dialects/src/clickhouse.rs
crates/lib-dialects/test/fixtures/dialects/clickhouse/rename.sql
crates/lib-dialects/test/fixtures/dialects/clickhouse/rename.yml

see https://github.com/sqlfluff/sqlfluff/pull/6073

feat: rename statement in clickhouse

---

crates/lib-core/src/dialects/syntax.rs
crates/lib-dialects/src/clickhouse.rs
crates/lib-dialects/test/fixtures/dialects/clickhouse/create_materialized_view.sql
crates/lib-dialects/test/fixtures/dialects/clickhouse/create_materialized_view.yml
crates/lib-dialects/test/fixtures/dialects/clickhouse/create_table.yml

see https://github.com/sqlfluff/sqlfluff/pull/6079

feat: tuple() and ENGINE MergeTree in clickhouse

---

crates/lib-dialects/src/clickhouse.rs
crates/lib-dialects/src/clickhouse_keywords.rs
crates/lib-dialects/test/fixtures/dialects/clickhouse/interval.sql
crates/lib-dialects/test/fixtures/dialects/clickhouse/interval.yml

see https://github.com/sqlfluff/sqlfluff/pull/6112

feat: better interval support in clickhouse

---

Cargo.lock
Cargo.toml
crates/lib/Cargo.toml

- **chore: bump strum from 0.27.1 to 0.27.2**
- **chore: bump strum_macros from 0.27.1 to 0.27.2**

chore: update strum

---

crates/lib-dialects/src/ansi.rs
crates/lib-dialects/src/clickhouse.rs
crates/lib-dialects/test/fixtures/dialects/clickhouse/in_implicit_array_tuple.sql
crates/lib-dialects/test/fixtures/dialects/clickhouse/in_implicit_array_tuple.yml
crates/lib-dialects/test/fixtures/dialects/clickhouse/in_operator.sql
crates/lib-dialects/test/fixtures/dialects/clickhouse/in_operator.yml
crates/lib-dialects/test/fixtures/dialects/clickhouse/in_table_cte.sql
crates/lib-dialects/test/fixtures/dialects/clickhouse/in_table_cte.yml

see https://github.com/sqlfluff/sqlfluff/pull/6667

feat: where in table, cte, array, tuple in clickhouse

---

crates/lib-dialects/src/clickhouse.rs
crates/lib-dialects/src/clickhouse_keywords.rs
crates/lib-dialects/test/fixtures/dialects/clickhouse/alter_table.sql
crates/lib-dialects/test/fixtures/dialects/clickhouse/alter_table.yml
crates/lib-dialects/test/fixtures/dialects/clickhouse/complex_table_definition.sql
crates/lib-dialects/test/fixtures/dialects/clickhouse/complex_table_definition.yml
crates/lib-dialects/test/fixtures/dialects/clickhouse/create_materialized_view.sql
crates/lib-dialects/test/fixtures/dialects/clickhouse/create_materialized_view.yml
crates/lib-dialects/test/fixtures/dialects/clickhouse/create_table.yml
crates/lib-dialects/test/fixtures/dialects/clickhouse/tuple_datatype.yml

see https://github.com/sqlfluff/sqlfluff/pull/6804

feat: support more types in create table, improve materialized views

---

crates/lsp/src/lib.rs

feat: handle buffer formatting in LSP

---

README.md
editors/code/README.md

doc: fix a wrong typo command in README

---

crates/lib-core/src/parser/segments.rs
crates/lib/src/rules/aliasing/al01.rs
crates/lib/src/rules/convention/cv05.rs
crates/lib/src/rules/layout/lt01.rs
crates/lib/src/rules/layout/lt02.rs
crates/lib/src/rules/layout/lt03.rs
crates/lib/src/rules/layout/lt04.rs
crates/lib/src/rules/layout/lt05.rs
crates/lib/src/rules/layout/lt11.rs
crates/lib/src/rules/structure/st08.rs
crates/lib/src/utils/reflow/elements.rs
crates/lib/src/utils/reflow/rebreak.rs
crates/lib/src/utils/reflow/reindent.rs
crates/lib/src/utils/reflow/respace.rs
crates/lib/src/utils/reflow/sequence.rs

- **feat: avoid clone on reflow sequence**
- **feat: further reduction in clones**

reflow sequence avoid clone

---

crates/lib-core/src/edit_type.rs
crates/lib-core/src/lib.rs
crates/lib-core/src/lint_fix.rs
crates/lib-core/src/linter.rs
crates/lib-core/src/parser/segments.rs
crates/lib-core/src/segments.rs
crates/lib/src/rules/convention/cv06.rs
crates/lib/src/rules/layout/lt08.rs
crates/lib/src/rules/layout/lt09.rs
crates/lib/src/utils/reflow/respace.rs

- **feat: improving lint fix structure**
- **chore: remove the edit type**

feat: improving lint fix
