Cargo.toml
Fixes the below warning:
> warning: virtual workspace defaulting to resolver = "1" despite one or more workspace members being on edition 2021 > which implies resolver = "2"
> note: to keep the current resolver, specify workspace.resolver = "1" in the workspace root's manifest
> note: to use the edition 2021 resolver, specify workspace.resolver = "2" in the workspace root's manifest
=> chore: specify `resolver = "2"` in the workspace Cargo.toml

.github/workflows/release.yml
Fix: #168 
The x86_64-apple-darwin target is disabled due to an error:
=> chore: workflow for release

Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/main.rs
Jemalloc is valuable because of its introspection API, which enables the acquisition of swift and precise memory usage data, overcoming the constraints faced by mallinfo.
=> chore: Add optional jemalloc support via feature flag

.github/workflows/release.yml
it seems due to this the workflow is failing
=> chore: upload file checksum once

rust-toolchain.toml
=> chore: pin Rust version that we are building with

crates/lib/src/core/linter/linter.rs, crates/lib/src/rules.rs, crates/lib/src/rules/aliasing.rs, crates/lib/src/rules/aliasing/AL03.rs, crates/lib/src/rules/aliasing/AL04.rs, crates/lib/src/rules/aliasing/AL05.rs, crates/lib/src/rules/aliasing/AL07.rs, crates/lib/src/rules/aliasing/AL08.rs, crates/lib/src/rules/ambiguous.rs, crates/lib/src/rules/ambiguous/AM01.rs, crates/lib/src/rules/capitalisation.rs, crates/lib/src/rules/capitalisation/CP01.rs, crates/lib/src/rules/capitalisation/CP02.rs, crates/lib/src/rules/capitalisation/CP03.rs, crates/lib/src/rules/capitalisation/CP04.rs, crates/lib/src/rules/capitalisation/CP05.rs, crates/lib/src/rules/convention.rs, crates/lib/src/rules/convention/CV02.rs, crates/lib/src/rules/layout.rs, crates/lib/src/rules/structure.rs, crates/lib/src/utils/analysis/select.rs
=> chore: standardize the method names for retrieving rules to `rules()` across all modules

.github/workflows/release.yml
- added workflow_dispatch so that we can manually trigger the publish step
- Secrets stored.
=> feat: add publish to cargo step on release

crates/cli/Cargo.toml, crates/lib/Cargo.toml
To address the issue described on the FAQ page (https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options):
=> chore: Disable benchmarking in CLI and library crates

crates/lsp/src/lib.rs
- adds the rule that is violated
- adds the source of the violation
=> feat: add diagnostic info to the lsp

.github/workflows/deploy.yml, .github/workflows/pr.yaml, playground/package.json, pnpm-lock.yaml
Reduces the WASM binary size from 5.01 MB to 2.79 MB for the playground.
=> internal(playground): improve wasm file size

.github/workflows/python-ci.yaml, rust-toolchain.toml
It looks like the python deployments have been failing because the rust-toolchain wasn't set and has been using `stable` by default when I think we want to use `nightly`.
This PR should fix that. I have tested in a previoud commit by changing the actions trigger to be 'pull request' and it built the artifacts fine for all the jobs: https://github.com/quarylabs/sqruff/actions/runs/11627091156
=> ci: fix maturin rust toolchain

crates/lib-core/src/parser/lexer.rs
=> refactor: add start-of-string anchor to regex patterns in lexer

crates/lib-dialects/src/duckdb.rs, crates/lib-dialects/test/fixtures/dialects/duckdb/load_statement.sql, crates/lib-dialects/test/fixtures/dialects/duckdb/load_statement.yml
Related to #882
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/quarylabs/sqruff/issues/882?shareId=c9b82efc-658a-4ca7-afbc-5e7c0392c14b).
=> Fix DuckDB LOAD syntax support

.github/workflows/docs.yml, Cargo.lock, Cargo.toml, crates/cli/Cargo.toml, crates/cli/src/commands.rs, crates/cli/src/github_action.rs, crates/lib-core/Cargo.toml, crates/lib-dialects/Cargo.toml
I noticed that specifying `default_value = "human"` in `#[arg]` directive does not rely on Default trait for Format enum which results in always defaults to human even on GitHub Actions.
So I replaced it to `default_value_t` which calls `Default::default` and sets default value depends on GitHub Actions or not properly.
I also implemented Display for Format enum since `default_value_t` requires `impl ToString`, but clippy suggests `impl Display` instead of `impl ToString`.
=> fix: github actions detection not working properly

editors/code/package.json, playground/package.json, pnpm-lock.yaml
- **chore: bump @eslint/js from 9.15.0 to 9.16.0**
- **chore: bump docker/setup-buildx-action from 2 to 3**
- **chore: bump indexmap from 2.6.0 to 2.7.0**
- **chore: bump tracing from 0.1.40 to 0.1.41**
- **chore: bump rustc-hash from 2.0.0 to 2.1.0**
- **chore: bump docker/build-push-action from 4 to 6**
- **perf(lexer): improve lexer performance by optimizing token matching**
- **chore: bump docker/setup-qemu-action from 2 to 3**
- **chore: bump docker/login-action from 2 to 3**
- **chore: bump @types/node from 22.9.4 to 22.10.1**
- **chore: bump eslint from 9.15.0 to 9.16.0**
=> updating eslint

crates/lib/src/core/config.rs
Previously, the `load_config_at_path` function removed the base filename and searched for filenames listed in `filename_options`, such as .sqruff and .sqlfluff. This fix changes the logic so that the filename_options list is only used if the file path is an existing directory. If instead the file path is an existing file, then simply load the config from the file.
fixes #1131. I recognize the presenting issue was already worked around by commit c69a0c81252f71ea1 but it still seems this should be fixed in `load_config_at_path`, yes?
=> fix: respect specified config filename

editors/code/package.json, playground/package.json, pnpm-lock.yaml
- **chore: bump @typescript-eslint/parser from 8.18.1 to 8.19.0**
- **chore: bump @typescript-eslint/eslint-plugin from 8.18.2 to 8.19.0**
=> update eslint parser

crates/cli/src/main.rs, crates/lib/src/cli/formatters.rs
The original implementation initialises the OutputStreamFormatter with the 'verbosity = 0`. However, the parameter `verbose = (0 - 2)` from the config does not override this value.
How similar to the original SQLFluff implementation do you want to keep scruff? There are a few additional parameters not yet set, which I would be happy to implement.
=> feat: Add verbosity config to OutputStreamFormatter

.github/workflows/pr.yaml, crates/cli/Cargo.toml, crates/cli/tests/jinja/.sqruff, crates/cli/tests/jinja/python.sql, crates/cli/tests/jinja/python.stderr, crates/cli/tests/ui_with_jinja.rs
=> chore: add jinja cli templater test

editors/code/package.json, playground/package.json, pnpm-lock.yaml
Bumps [@eslint/js](https://github.com/eslint/eslint/tree/HEAD/packages/js) and [@types/eslint__js](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/eslint__js). These dependencies needed to be updated together.
Updates `@eslint/js` from 9.20.0 to 9.21.0
- [Release notes](https://github.com/eslint/eslint/releases)
- [Changelog](https://github.com/eslint/eslint/blob/main/CHANGELOG.md)
- [Commits](https://github.com/eslint/eslint/commits/v9.21.0/packages/js)
Updates `@types/eslint__js` from 8.42.3 to 9.14.0
- [Release notes](https://github.com/DefinitelyTyped/DefinitelyTyped/releases)
- [Commits](https://github.com/DefinitelyTyped/DefinitelyTyped/commits/HEAD/types/eslint__js)
---
updated-dependencies:
- dependency-name: "@eslint/js"
dependency-type: direct:development …
=> chore: bump @eslint/js and @types/eslint__js

.github/workflows/release.yml
Related to #1348
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/quarylabs/sqruff/pull/1392?shareId=5f0b03e3-f482-4c02-9936-1c053852da59).
=> Add attestation for GitHub release artifacts

.github/workflows/python-ci.yml
@benfdking 
It looks like the release didn't work properly/find any files and there is no new release on pypi. I think this might be because of changing line 404 in `python-ci.yml` from:
```yaml
args: --non-interactive --skip-existing wheels-*/*
```
to:
```yaml          
args: --non-interactive --skip-existing artifacts-*/
```
**We are using an artifacts-*/ prefix for the binaries however I believe we are still using the 'wheels-' prefix for the wheels** we are uploading as artifacts so we still want to use the `wheels` prefix in the release args on line 404.
Hopefully this PR will fix the python release.
=> fix:python release

.github/workflows/python-ci.yml
fix:working dir for python wheel publish.
I tested and you can see that [the files are now being picked up](https://github.com/quarylabs/sqruff/actions/run
=> fix:working dir for python wheel publish.

crates/lib-dialects/src/sqlite.rs, crates/lib-dialects/test/fixtures/dialects/sqlite/delete.sql, crates/lib-dialects/test/fixtures/dialects/sqlite/delete.yml, crates/lib-dialects/test/fixtures/dialects/sqlite/update.sql, crates/lib-dialects/test/fixtures/dialects/sqlite/update.yml
Queries including the `RETURNING` clause in `DELETE` and `UPDATE` statements and what comes after them were not being properly parsed in the sqlite dialect. 
I am not sure if this is the best way to go about fixing this but this patch got both the `DELETE` and `UPDATE` queries with a `RETURNING` clause formatting properly. 
Sqlite supports [DELETE](https://sqlite.org/lang_delete.html), [INSERT](https://sqlite.org/lang_insert.html), and [UPDATE](https://sqlite.org/lang_update.html) statements. https://sqlite.org/lang_returning.html
Related to https://github.com/quarylabs/sqruff/issues/1028
=> fix: add ability to parse returning in sqlite delete update

crates/lib-dialects/src/sqlite.rs, crates/lib-dialects/test/fixtures/dialects/sqlite/select.yml, crates/lib-dialects/test/fixtures/dialects/sqlite/window.sql, crates/lib-dialects/test/fixtures/dialects/sqlite/window.yml
Was having an issue where this query wasn't being parsed properly in the sqlite dialect:
```
SELECT
some_val AS sv,
ROW_NUMBER() OVER (PARTITION BY name),
other_val AS ov
FROM tablename;
``` 
I think this patch reflects what the diagram here represents: https://sqlite.org/windowfunctions.html
The previous query gets properly formatted with this patch.
=> fix: add sqlite window function grammar spec

crates/lib/src/templaters/placeholder.rs, docs/templaters.md
I'm not a Rust expert, but opening this as a conversation starter. Not sure if this is all it is needed.
So, I've been using sqlc in a golang project and I tried to use named variables as described [here](https://docs.sqlc.dev/en/latest/howto/named_parameters.html) and it caused problems with sqruff formatting.
This is my attempt at supporting that.
EDIT: Tested with the following config in my project and it worked perfectly
```
[sqruff]
templater = placeholder
[sqruff:templater:placeholder]
param_style = at
```
=> feat: accept sqlc style placeholders

CONTRIBUTING.md
This updates `contributing.md` to reflect what appears to be the correct way to set up your development environment for the first time. The existing instructions weren't complete as `cargo test` fails if the virtual environment isn't set up already.
I'm happy to make edits to reflect the correct setup. These steps worked for me.
=> docs: updating contributing

crates/lib/test/fixtures/rules/std_rule_cases/CP01_CP03.yml, crates/lib/tests/rules.rs
I think https://github.com/quarylabs/sqruff/pull/1698 broke formatting for functions (I didn't verify that this exact PR brakes it), see the test in 7d9a438dfc68a5b9b4f6f04430bcbc78b8e0d330
I checked that this test works correctly on v0.27.0, but it doesn't work on main
cc: @Fank @benfdking
=> chore: add test for keywords: upper and functions: lower

crates/lib-dialects/src/clickhouse.rs, crates/lib-dialects/test/fixtures/dialects/clickhouse/format.sql, crates/lib-dialects/test/fixtures/dialects/clickhouse/format.yml, crates/lib-dialects/test/fixtures/dialects/clickhouse/into_outfile.sql, crates/lib-dialects/test/fixtures/dialects/clickhouse/into_outfile.yml
see https://github.com/sqlfluff/sqlfluff/pull/6065
This is not 1:1 translation of changes from sqlfluff
IMO formats should not be treated as keyword, because:
* capitalisation rules should not be applied to formats
* I want to avoid maintaining a list of formats
=> feat: format and into outfile in clickhouse
